config/routes.rb
Nmi::Application.routes.draw do

  root :to => 'home#index'

  devise_for :users
  devise_for :users, :path => "webmaster"

  namespace :webmaster do
    resources :categories do
       collection do
        get :category_childrens
      end
    end
    resources :users
    resources :brands do
      collection do
        get :add_new_brand
        post :create_new_brand
      end
    end
    resources :products do
      collection do
        get :search_attribute_name
        get :search_categories
      end
    end
    resources :images do
      collection do
        get :sort
        post :upload_image
        get :delete_image
      end
    end
    get "home/index"
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	attr_accessible :name, :image_attributes, :parent_id, :ancestry
  has_one :image, as: :imageable, dependent: :destroy,  :class_name => 'Image'
	accepts_nested_attributes_for :image, :reject_if => lambda { |t| t[:image].nil?}, :allow_destroy => true

  has_ancestry

	def self.get_all_parent
		where(:ancestry => nil)
	end

  def self.get_all_sub_categories
    sub_cat = []
    cat = self.where(:ancestry => nil)
    cat.each do |sub|
      sub_cat << sub.children
    end
    return sub_cat.flatten
  end

  def self.get_all_sub_categories_level_1
    sub_cat = []
    sub_cat_1 = []
    cat = self.where(:ancestry => nil)
    cat.each do |sub|
      sub_cat << sub.children
    end
    sub_cat.flatten.each do |sub_1|
      sub_cat_1 << sub_1.children
    end

    return sub_cat_1.flatten
  end

  def self.get_all_sub_categories_level_1
    sub_cat = []
    sub_cat_1 = []
    cat = self.where(:ancestry => nil)
    cat.each do |sub|
      sub_cat << sub.children
    end
    sub_cat.flatten.each do |sub_1|
      sub_cat_1 << sub_1.children
    end
    return sub_cat_1.flatten
  end

  def self.get_all_sub_categories_level_2
    sub_cat = []
    sub_cat_1 = []
    sub_cat_2 = []
    cat = self.where(:ancestry => nil)
    cat.each do |sub|
      sub_cat << sub.children
    end
    sub_cat.flatten.each do |sub_1|
      sub_cat_1 << sub_1.children
    end
    sub_cat_1.flatten.each do |sub_2|
      sub_cat_2 << sub_2.children
    end
    return sub_cat_2.flatten
  end

  def get_all_children_level_1
    sub_cat = []
    sub_cat_1 = []
    sub_cat << self.children
    sub_cat.flatten.each do |sub_1|
      sub_cat_1 << sub_1.children
    end
    return sub_cat_1.flatten
  end

  def get_all_children_level_2
    sub_cat = []
    sub_cat_1 = []
    sub_cat_2 = []
    sub_cat << self.children
    sub_cat.flatten.each do |sub_1|
      sub_cat_1 << sub_1.children
    end
    sub_cat_1.flatten.each do |sub_2|
      sub_cat_2 << sub_2.children
    end
    return sub_cat_2.flatten
  end

  # def get_root_category

  # end

  # def get_children
  # end

  # def get_all_children
  # end
end

app/models/webmaster.rb
module Webmaster
  def self.table_name_prefix
    'webmaster_'
  end
end

app/controllers/webmaster/brands_controller.rb
class Webmaster::BrandsController < ApplicationController

  before_filter :authenticate_user!
  load_and_authorize_resource

  layout 'webmaster'
  def index
    @brands = Brand.all
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(params[:brand])
    respond_to do |format|
      if @brand.save
        if params[:commit] == "Add Brand"
          format.html { redirect_to new_webmaster_product_path }
        else
           format.html { redirect_to webmaster_brand_path(@brand), notice: 'Brand was successfully created.' }
        end
        #format.json { render json: @webmaster_category, status: :created, location: @webmaster_category }
      else
        format.html { render action: "new" }
      end
    end
  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def show
     @brand = Brand.find(params[:id])
  end

  def update
    @brand = Brand.find(params[:id])

    respond_to do |format|
      if @brand.update_attributes(params[:brand])
        format.html { redirect_to webmaster_brand_path(@brand), notice: 'Brand was successfully updated.' }
        #format.json { head :no_content }
      else
        format.html { render action: "edit" }
        #format.json { render json: @webmaster_category.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_new_brand
    @brand = Brand.new
    respond_to do |format|
      format.js
    end
  end



  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to webmaster_brands_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/webmaster/categories_controller.rb
class Webmaster::CategoriesController < ApplicationController
 before_filter :authenticate_user!
 #before_filter :authorize_admin
 load_and_authorize_resource

 layout 'webmaster'

  # GET /webmaster/categories
  # GET /webmaster/categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
     # format.json { render json: @webmaster_categories }
    end
  end

  def category_childrens
    @parent_category = Category.get_all_parent
  end

  # GET /webmaster/categories/1
  # GET /webmaster/categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      #format.json { render json: @webmaster_category }
    end
  end

  # GET /webmaster/categories/new
  # GET /webmaster/categories/new.json
  def new
    @category =  Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /webmaster/categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /webmaster/categories
  # POST /webmaster/categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to webmaster_category_path(@category), notice: 'Category was successfully created.' }
        #format.json { render json: @webmaster_category, status: :created, location: @webmaster_category }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /webmaster/categories/1
  # PUT /webmaster/categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to webmaster_category_path(@category), notice: 'Category was successfully updated.' }
        #format.json { head :no_content }
      else
        format.html { render action: "edit" }
        #format.json { render json: @webmaster_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webmaster/categories/1
  # DELETE /webmaster/categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to webmaster_categories_url }
      format.json { head :no_content }
    end
  end

  protected

  def authorize_admin
    authorize! :manage, :all
  end
end

app/controllers/webmaster/home_controller.rb
class Webmaster::HomeController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  layout 'webmaster'
  def index
  end
end

app/controllers/webmaster/images_controller.rb
class Webmaster::ImagesController < ApplicationController

	def delete_image
    @image = Image.find(params[:id])
    @images = Image.where(:product_token => @image.product_token).order("position")
    @image.destroy
    respond_to do |format|
      format.js 
    end
  end

  def upload_image
    @image = Image.create(params[:image])
    @images = Image.where(:product_token => @image.product_token).order("position")
  end 

  def sort
    params[:image].each_with_index do |id, index|
      Image.update_all({position: index+1}, {id: id})
    end
    render nothing: true
  end

end

app/controllers/webmaster/products_controller.rb
class Webmaster::ProductsController < ApplicationController
 before_filter :authenticate_user!
 load_and_authorize_resource
 layout 'webmaster'


  # GET /webmaster/categories
  # GET /webmaster/categories.json
  def index
    if current_user.role == 'super_admin'
      @products = Product.all
    else
      @products = current_user.products
    end

    respond_to do |format|
      format.html # index.html.erb
     # format.json { render json: @webmaster_categories }
    end
  end

  # GET /webmaster/categories/1
  # GET /webmaster/categories/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      #format.json { render json: @webmaster_category }
    end
  end

  # GET /webmaster/categories/new
  # GET /webmaster/categories/new.json
  def new
    @product =  Product.new
    if @product.token.nil?
      @product.token = @product.generate_token
    end
    @images = Image.where(:product_token => @product.token).order("position")
    respond_to do |format|
      format.html # new.html.erb
      #format.json { render json: @product }
    end
  end

  # GET /webmaster/categories/1/edit
  def edit
    @product = Product.find(params[:id])
    @images = @product.images.order('position')
  end

  # POST /webmaster/categories
  # POST /webmaster/categories.json
  def create
    @product = Product.new(params[:product])
    @images = Image.where(:product_token => params[:product][:token])
    respond_to do |format|
      if @product.save
        @images.each do |image|
          image.update_attributes(imageable_id: @product.id, imageable_type: @product.class.name)
        end
        format.html { redirect_to webmaster_product_path(@product), notice: 'Product was successfully created.' }
        #format.json { render json: @webmaster_category, status: :created, location: @webmaster_category }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /webmaster/categories/1
  # PUT /webmaster/categories/1.json
  def update
    @product = Product.find(params[:id])
    @images = Image.where(:product_token => params[:product][:token])
    respond_to do |format|
      if @product.update_attributes(params[:product])
        @images.each do |image|
          image.update_attributes(imageable_id: @product.id, imageable_type: @product.class.name)
        end
        format.html { redirect_to webmaster_product_path(@product), notice: 'Product was successfully updated.' }
        #format.json { head :no_content }
      else
        format.html { render action: "edit" }
        #format.json { render json: @webmaster_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webmaster/categories/1
  # DELETE /webmaster/categories/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to webmaster_products_url }
      format.json { head :no_content }
    end
  end

  def search_attribute_name
    @results =  ProductItem.where("name LIKE ?", "%#{params[:q]}%")
    respond_to do |format|
      format.json
    end
  end

  def search_categories
    @categories = Category.where(:id=> params[:sub_cat_id]).first.children
  end
end

app/controllers/webmaster/users_controller.rb
class Webmaster::UsersController < ApplicationController
  before_filter :authenticate_user!
  #before_filter :authorize_admin
  load_and_authorize_resource
  layout 'webmaster'
  #before_filter :authenticate_user!
  def index
  	@users = User.all
  end

  def edit
  	@user = User.find(params[:id])
  end

  def show
  	 @user = User.find(params[:id])
  end

  def update
	  @user = User.find(params[:id])

	  if @user.update_attributes(params[:user])
	    redirect_to webmaster_user_url(@user)
	  else
	    render 'edit'
	  end
  end
  def destroy
  	@user = User.find(params[:id])
  	@user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
    end
  end

  protected
  # def authorize_admin
  #   authorize! :manage, :all
  # end

end

app/helpers/webmaster/brands_helper.rb
module Webmaster::BrandsHelper
end

app/helpers/webmaster/categories_helper.rb
module Webmaster::CategoriesHelper
end

app/helpers/webmaster/home_helper.rb
module Webmaster::HomeHelper
end

app/helpers/webmaster/image_helper.rb
module Webmaster::ImageHelper
end

app/helpers/webmaster/users_helper.rb
module Webmaster::UsersHelper
end

app/views/webmaster/categories/category_childrens.html.erb
<div id="page-wrapper">
  <div id="page-inner">
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <span> Category Lists </span>
            <%= link_to 'New', new_webmaster_category_path, class: 'pull-right' %>
          </div>
          <div class="panel-body">
            <div class="table-responsive">
              <table class="table table-striped table-bordered table-hover">
                <tr>
                  <th>Parent</th>
                  <th>First children</th>
                  <th>Second children</th>
                  <th>Third children</th>
                </tr>

                <% @parent_category.order(:name).each do |category| %>
                  <tr>
                    <td><%= category.name %></td>
                    <td></td>
                    <td></td>
                    <td></td>
                      <% category.children.order(:name).each do |sub| %>
                        <tr>
                          <td></td>
                          <td><%= sub.name %></td>
                          <td></td>
                          <td></td>
                          <% sub.children.order(:name).each do |ch|%>
                            <tr>
                              <td></td>
                              <td></td>
                              <td><%= ch.name %></td>
                              <% ch.children.order(:name).each do |c|%>
                                <tr>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                                  <td><%= c.name %></td>
                                </tr>
                              <% end %>
                             </tr>
                          <% end %>
                        </tr>
                      <% end %>
                  </tr>
                <% end %>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/webmaster/categories/edit.html.erb
<div id="page-wrapper" >
  <div id="page-inner">
    <div class="row">
      <div class="row">
        <div class="col-lg-12">
          <div class="panel panel-default">
            <div class="panel-heading">
                Edit Cateory
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-lg-6">    
									<%= form_for [:webmaster, @category] do |f| %>
									  <% if @category.errors.any? %>
									    <div id="error_explanation">
									      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this webmaster_category from being saved:</h2>

									      <ul>
									      <%  @category.errors.full_messages.each do |msg| %>
									        <li><%= msg %></li>
									      <% end %>
									      </ul>
									    </div>
									  <% end %>

									  <div class="form-group">
									    <%= f.label :name %><br />
									    <%= f.text_field :name %>
									  </div>
									  <div class="form-group">
									    <%= f.label :parent_id %><br />
									    <%= f.select :parent_id, Category.all.collect {|p| [ p.name, p.id ] },  :selected => f.object.parent_id %>
									  </div>
									  <div class="form-group">
                    <%= f.fields_for :image_attributes  do |i| %>
                      <%= i.file_field :image %>
                    <% end %>
                    </div>
                    <% if @category.image.present? %>
                      <%= image_tag @category.image.image.thumb.url%>
                    <% end %>

									  <div class="form-group">
									    <%= f.submit %>
									  </div>
									<% end %>



									<%= link_to 'Back', webmaster_categories_path %>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/webmaster/categories/index.html.erb
<div id="page-wrapper">
  <div id="page-inner">
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading">
             <span> Category Lists </span>
             <%= link_to 'New', new_webmaster_category_path, class: 'pull-right' %>

          </div>
          <div class="panel-body">
            <div class="table-responsive">

              <table class="table table-striped table-bordered table-hover">
                <tr>
                  <th>Name</th>
                  <th></th>
                  <th></th>
                  <th></th>
                </tr>

              <% @categories.each do |category| %>
                <tr>
                  <td><%= category.name %></td>
                  <td><%= link_to 'Show', webmaster_category_path(category) %></td>
                  <td><%= link_to 'Edit', edit_webmaster_category_path(category) %></td>
                  <td><%= link_to 'Destroy', webmaster_category_path(category), confirm: 'Are you sure?', method: :delete %></td>
                </tr>
              <% end %>
              </table>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/webmaster/categories/new.html.erb
<div id="page-wrapper" >
  <div id="page-inner">
    <div class="row">
      <div class="row">
        <div class="col-lg-12">
          <div class="panel panel-default">
            <div class="panel-heading">
                New Cateory
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-lg-6">
									<%= form_for [:webmaster, @category] do |f| %>
									  <% if @category.errors.any? %>
									    <div id="error_explanation">
									      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this webmaster_category from being saved:</h2>

									      <ul>
									      <%  @category.errors.full_messages.each do |msg| %>
									        <li><%= msg %></li>
									      <% end %>
									      </ul>
									    </div>
									  <% end %>

									  <div class="form-group">
									    <%= f.label :name %><br />
									    <%= f.text_field :name %>
									  </div>
									  <div class="form-group">
									    <%= f.label :parent_id %><br />
									    <%= f.collection_select :parent_id, Category.all, :id, :name, { include_blank: true} %>
									  </div>

                    <div class="form-group">
                    <%= f.fields_for :image_attributes  do |i| %>
                      <%= i.file_field :image %>
                    <% end %>
                    </div>

									  <div class="form-group">
									    <%= f.submit %>
									  </div>
									<% end %>



									<%= link_to 'Back', webmaster_categories_path %>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/webmaster/categories/show.html.erb
<div id="page-wrapper">
  <div id="page-inner">
    <div class="row">
      <div class="col-md-8 col-sm-12 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= @category.name %>
          </div>
          <div class="panel-body">
						<p>
						  <b>Name:</b>
						  <%= @category.name %>
						</p>

						<p>
						  <b>Parent:</b>
						  <%= @category.parent.try(:name)%>
						</p>

						<p>
						  <b>Image:</b>
						  <% if @category.image.present? %>
						    <%= image_tag @category.image.image.thumb.url%>
						  <% end %>
						</p>


						<%= link_to 'Edit', edit_webmaster_category_path(@category) %> |
						<%= link_to 'Back', webmaster_categories_path %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>