config/routes.rb
Nmi::Application.routes.draw do

  root :to => 'home#index'

  devise_for :users
  devise_for :users, :path => "webmaster"

  namespace :webmaster do
    resources :categories do
       collection do
        get :category_childrens
      end
    end
    resources :users
    resources :brands do
      collection do
        get :add_new_brand
        post :create_new_brand
      end
    end
    resources :products do
      collection do
        get :search_attribute_name
        get :search_categories
      end
    end
    resources :images do
      collection do
        get :sort
        post :upload_image
        get :delete_image
      end
    end
    get "home/index"
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :images, as: :imageable, dependent: :destroy,  :class_name => 'Image'
  belongs_to :brand
  belongs_to :user
  has_many :products_product_items, dependent: :destroy
  has_many :product_items, through: :products_product_items

	attr_accessible :title, :description, :price, :brand_id, :user_id, :category_id, :part_number,
                  :images_attributes, :token, :product_image, :product_items_attributes,
                  :products_product_items_attributes, :sub_category_id, :sub_category_first_id,
                  :sub_category_second_id, :store, :is_active
	accepts_nested_attributes_for :images, :allow_destroy => true
  accepts_nested_attributes_for :products_product_items,
           :reject_if => :all_blank,
           :allow_destroy => true
  accepts_nested_attributes_for :product_items

  # attr_accessible :value, :products_product_items_attributes
  # accepts_nested_attributes_for :products_product_items
  validates :title, :description, :price, :brand_id, :part_number,:product_image, :category_id, presence: true

  mount_uploader :product_image, ImageUploader

  after_create :generate_uniq_id

  STORE = [['New store', 'new_store'], ['Old store', 'old_store']]

  def generate_token
    self.token = loop do
      random_token = SecureRandom.urlsafe_base64
      break random_token unless Product.where(token: random_token).exists?
    end
  end

  protected

  def generate_uniq_id
  	self.uniq_code = "NMI-#{self.combination}"
  	self.save!
  end

  def combination
  	str = ''
  	product_id = self.id.to_s.length
    case product_id
    when 1
      str = "00000#{self.id}"
    when 2
      str = "0000#{self.id}"
    when 3
    	str = "000#{self.id}"
    when 4
    	str = "00#{self.id}"
    when 5
      str = "0#{self.id}"
    when 6
      str = "#{self.id}"
    else
    	str = "#{self.id}"
    end
    return str
  end

end

app/models/webmaster.rb
module Webmaster
  def self.table_name_prefix
    'webmaster_'
  end
end

app/controllers/webmaster/brands_controller.rb
class Webmaster::BrandsController < ApplicationController

  before_filter :authenticate_user!
  load_and_authorize_resource

  layout 'webmaster'
  def index
    @brands = Brand.all
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(params[:brand])
    respond_to do |format|
      if @brand.save
        if params[:commit] == "Add Brand"
          format.html { redirect_to new_webmaster_product_path }
        else
           format.html { redirect_to webmaster_brand_path(@brand), notice: 'Brand was successfully created.' }
        end
        #format.json { render json: @webmaster_category, status: :created, location: @webmaster_category }
      else
        format.html { render action: "new" }
      end
    end
  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def show
     @brand = Brand.find(params[:id])
  end

  def update
    @brand = Brand.find(params[:id])

    respond_to do |format|
      if @brand.update_attributes(params[:brand])
        format.html { redirect_to webmaster_brand_path(@brand), notice: 'Brand was successfully updated.' }
        #format.json { head :no_content }
      else
        format.html { render action: "edit" }
        #format.json { render json: @webmaster_category.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_new_brand
    @brand = Brand.new
    respond_to do |format|
      format.js
    end
  end



  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to webmaster_brands_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/webmaster/categories_controller.rb
class Webmaster::CategoriesController < ApplicationController
 before_filter :authenticate_user!
 #before_filter :authorize_admin
 load_and_authorize_resource

 layout 'webmaster'

  # GET /webmaster/categories
  # GET /webmaster/categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
     # format.json { render json: @webmaster_categories }
    end
  end

  def category_childrens
    @parent_category = Category.get_all_parent
  end

  # GET /webmaster/categories/1
  # GET /webmaster/categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      #format.json { render json: @webmaster_category }
    end
  end

  # GET /webmaster/categories/new
  # GET /webmaster/categories/new.json
  def new
    @category =  Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /webmaster/categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /webmaster/categories
  # POST /webmaster/categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to webmaster_category_path(@category), notice: 'Category was successfully created.' }
        #format.json { render json: @webmaster_category, status: :created, location: @webmaster_category }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /webmaster/categories/1
  # PUT /webmaster/categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to webmaster_category_path(@category), notice: 'Category was successfully updated.' }
        #format.json { head :no_content }
      else
        format.html { render action: "edit" }
        #format.json { render json: @webmaster_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webmaster/categories/1
  # DELETE /webmaster/categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to webmaster_categories_url }
      format.json { head :no_content }
    end
  end

  protected

  def authorize_admin
    authorize! :manage, :all
  end
end

app/controllers/webmaster/home_controller.rb
class Webmaster::HomeController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  layout 'webmaster'
  def index
  end
end

app/controllers/webmaster/images_controller.rb
class Webmaster::ImagesController < ApplicationController

	def delete_image
    @image = Image.find(params[:id])
    @images = Image.where(:product_token => @image.product_token).order("position")
    @image.destroy
    respond_to do |format|
      format.js 
    end
  end

  def upload_image
    @image = Image.create(params[:image])
    @images = Image.where(:product_token => @image.product_token).order("position")
  end 

  def sort
    params[:image].each_with_index do |id, index|
      Image.update_all({position: index+1}, {id: id})
    end
    render nothing: true
  end

end

app/controllers/webmaster/products_controller.rb
class Webmaster::ProductsController < ApplicationController
 before_filter :authenticate_user!
 load_and_authorize_resource
 layout 'webmaster'


  # GET /webmaster/categories
  # GET /webmaster/categories.json
  def index
    if current_user.role == 'super_admin'
      @products = Product.all
    else
      @products = current_user.products
    end

    respond_to do |format|
      format.html # index.html.erb
     # format.json { render json: @webmaster_categories }
    end
  end

  # GET /webmaster/categories/1
  # GET /webmaster/categories/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      #format.json { render json: @webmaster_category }
    end
  end

  # GET /webmaster/categories/new
  # GET /webmaster/categories/new.json
  def new
    @product =  Product.new
    if @product.token.nil?
      @product.token = @product.generate_token
    end
    @images = Image.where(:product_token => @product.token).order("position")
    respond_to do |format|
      format.html # new.html.erb
      #format.json { render json: @product }
    end
  end

  # GET /webmaster/categories/1/edit
  def edit
    @product = Product.find(params[:id])
    @images = @product.images.order('position')
  end

  # POST /webmaster/categories
  # POST /webmaster/categories.json
  def create
    @product = Product.new(params[:product])
    @images = Image.where(:product_token => params[:product][:token])
    respond_to do |format|
      if @product.save
        @images.each do |image|
          image.update_attributes(imageable_id: @product.id, imageable_type: @product.class.name)
        end
        format.html { redirect_to webmaster_product_path(@product), notice: 'Product was successfully created.' }
        #format.json { render json: @webmaster_category, status: :created, location: @webmaster_category }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /webmaster/categories/1
  # PUT /webmaster/categories/1.json
  def update
    @product = Product.find(params[:id])
    @images = Image.where(:product_token => params[:product][:token])
    respond_to do |format|
      if @product.update_attributes(params[:product])
        @images.each do |image|
          image.update_attributes(imageable_id: @product.id, imageable_type: @product.class.name)
        end
        format.html { redirect_to webmaster_product_path(@product), notice: 'Product was successfully updated.' }
        #format.json { head :no_content }
      else
        format.html { render action: "edit" }
        #format.json { render json: @webmaster_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webmaster/categories/1
  # DELETE /webmaster/categories/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to webmaster_products_url }
      format.json { head :no_content }
    end
  end

  def search_attribute_name
    @results =  ProductItem.where("name LIKE ?", "%#{params[:q]}%")
    respond_to do |format|
      format.json
    end
  end

  def search_categories
    @categories = Category.where(:id=> params[:sub_cat_id]).first.children
  end
end

app/controllers/webmaster/users_controller.rb
class Webmaster::UsersController < ApplicationController
  before_filter :authenticate_user!
  #before_filter :authorize_admin
  load_and_authorize_resource
  layout 'webmaster'
  #before_filter :authenticate_user!
  def index
  	@users = User.all
  end

  def edit
  	@user = User.find(params[:id])
  end

  def show
  	 @user = User.find(params[:id])
  end

  def update
	  @user = User.find(params[:id])

	  if @user.update_attributes(params[:user])
	    redirect_to webmaster_user_url(@user)
	  else
	    render 'edit'
	  end
  end
  def destroy
  	@user = User.find(params[:id])
  	@user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
    end
  end

  protected
  # def authorize_admin
  #   authorize! :manage, :all
  # end

end

app/helpers/webmaster/brands_helper.rb
module Webmaster::BrandsHelper
end

app/helpers/webmaster/categories_helper.rb
module Webmaster::CategoriesHelper
end

app/helpers/webmaster/home_helper.rb
module Webmaster::HomeHelper
end

app/helpers/webmaster/image_helper.rb
module Webmaster::ImageHelper
end

app/helpers/webmaster/users_helper.rb
module Webmaster::UsersHelper
end

app/views/webmaster/products/_attribute_suggest_result.html.erb
<a>{{value}}</a>

app/views/webmaster/products/_attribute_suggestion.html.erb
<script type="text/javascript">
  $(document).ready(function (e) {
    // instantiate the bloodhound suggestion engine
    var hive_suggest_results = new Bloodhound({
      datumTokenizer: function (d) {
        return Bloodhound.tokenizers.whitespace(d.value);
      },
      queryTokenizer: Bloodhound.tokenizers.whitespace,
      limit: 10,
      remote: {
        url: '<%= search_attribute_name_webmaster_products_path(format: :json) %>?q=%QUERY',
        filter: function (results) {
          return $.map(results, function (result) {
            return {
              value: result.name
            };
          });
        }
      }
    });

    // initialize the bloodhound suggestion engine
    hive_suggest_results.initialize();

    function call_autocomplete(obj_id){
      $("#"+obj_id).typeahead({
        hint: true,
        highlight: true,
        minLength: 1
      }, {
        displayKey: 'value',
        source: hive_suggest_results.ttAdapter(),
        templates: {
          empty: [
            '<div>',
            'No result',
            '</div>'
          ].join('\n'),
          suggestion: Handlebars.compile('<%= j(render(partial: 'attribute_suggest_result')) %>')
        }
      }/* more data sets if needed */);
    }

    // instantiate the typeahead UI
    // $('.item_name').each(function() {
    //  var divID = '#' + $(this).attr('id');
    //  alert(divID);

    // });

    $("#product_items").bind("cocoon:after-insert", function() {
      $(".item_name").each(function(){
        if($(this).attr('id') !== undefined){
          if(!$(this).hasClass('tt-input')){
            call_autocomplete($(this).attr('id'));
          }
        }
      });
    });
  });
</script>

app/views/webmaster/products/_products_product_item_fields.html.erb
<li class="nested-fields">
  <div class="controls">
    <%= f.fields_for :product_item do |item| %>
      <%= item.label :name %>
      <%= item.text_field :name, class: 'item_name' %>
      <br/>
      <%= item.label :item_type %>
      <%= item.select(:item_type, options_for_select(ProductItem::DATA_TYPES ,:selected => item.object.item_type))  %>
      <br/>
    <% end %>
    <%= f.label :value %>
    <%= f.text_field :value %>
    <%= link_to_remove_association "remove", f %>
  </div>
</li>

app/views/webmaster/products/_select_category.html.erb
<div class="form-group" id='sub_category'>
  <%= label_tag 'Select sub category name' %><br />
  <%= select_tag 'product[sub_category_id]', options_from_collection_for_select(sub_categories, :id, :name, selected: selected_value), {:include_blank => 'Select sub category'}%>
</div>

<script>

    $('#product_sub_category_id').change(function(){
      var val_id =  $('#product_sub_category_id :selected').val();
      $.ajax({
          type: 'GET',
          url: "<%= search_categories_webmaster_products_path %>",
          data: {"sub_cat_id": val_id, "type": "sub_category"}
      });

    });
</script>

app/views/webmaster/products/_select_category_first.html.erb
<div class="form-group" id='sub_category'>
  <%= label_tag 'Select sub category level first' %><br />
  <%= select_tag 'product[sub_category_first_id]', options_from_collection_for_select(sub_categories, :id, :name, selected: selected_value),  {:include_blank => 'Select sub category'}%>
</div>

<script>

    $('#product_sub_category_first_id').change(function(){
      var val_id =  $('#product_sub_category_first_id :selected').val();
      $.ajax({
          type: 'GET',
          url: "<%= search_categories_webmaster_products_path %>",
          data: {"sub_cat_id": val_id, "type": "sub_category_first"}
      });

    });
</script>

app/views/webmaster/products/_select_category_second.html.erb
<div class="form-group" id='sub_category_second'>
  <%= label_tag 'Select sub category level second' %><br />
  <%= select_tag 'product[sub_category_second_id]', options_from_collection_for_select(sub_categories, :id, :name, selected: selected_value),  {:include_blank => 'Select sub category'}%>
</div>

<script>

    $('#product_sub_category_second_id').change(function(){
      var val_id =  $('#product_sub_category_second_id :selected').val();
      $.ajax({
          type: 'GET',
          url: "<%= search_categories_webmaster_products_path %>",
          data: {"sub_cat_id": val_id}
      });

    });
</script>

app/views/webmaster/products/_upload_image.html.erb
<%= form_for Image.new,:url=>upload_image_webmaster_images_path, :id=> 'new_image', remote: true  do |f| %>
  <%= f.hidden_field :product_token, value: @product.token %>
    <span class="btn btn-mini fileinput-button">
      <i class="icon-plus"></i>
      	<button type="submit" class="btn btn-default">Upload photos</button>
  			<%= f.file_field :image, multiple: true, name: "image[image]" %>
    </span>
    <br/>
<% end %>

app/views/webmaster/products/edit.html.erb
<div id="page-wrapper" >
  <div id="page-inner">
    <div class="row">
      <div class="row">
        <div class="col-lg-12">
          <div class="panel panel-default">
            <div class="panel-heading">
                Edit Product
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-lg-6">
									<%= form_for [:webmaster, @product] do |f| %>
									  <% if @product.errors.any? %>
									    <div id="error_explanation">
									      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

									      <ul>
									      <%  @product.errors.full_messages.each do |msg| %>
									        <li><%= msg %></li>
									      <% end %>
									      </ul>
									    </div>
									  <% end %>
                    <%= f.hidden_field :token, :value=>@product.token %>

                    <%= f.hidden_field :user_id, :value=> current_user.id %>

                    <div class="form-group">
                      <%= f.label 'Select brand name' %><br />
                      <%= f.collection_select :brand_id, Brand.all, :id, :name %>
                    </div>

									  <div class="form-group">
									    <%= f.label :title %><br />
									    <%= f.text_field :title %>
									  </div>
									  <div class="form-group">
									    <%= f.label :description %><br />
									    <%= f.text_area :description, :cols => "50", :rows => "8" %>
									  </div>

                    <div class="form-group" id='categories'>
                      <%= f.label 'Store' %><br />
                      <%= f.select(:store, options_for_select(Product::STORE, selected: f.object.store))%>
                    </div>
                    <div class="form-group">
                      <%= f.label 'Prodcut status' %><br />
                      <div class="checkbox">
                        <%= f.check_box :is_active %>
                        <% if f.object.is_active? %>
                          <span> Disable</span>
                        <% else %>
                          <span> Enable</span>
                        <% end %>
                      </div>
                    </div>

									  <div class="form-group">
									    <%= f.label :product_image %><br />
									    <%= f.file_field :product_image %>
									  </div>
									  <div class="form-group">
									    <% if @product.product_image.present? %>
									      <%= image_tag @product.product_image.thumb.url%>
                      <% end %>
									  </div>

									  <div class="form-group">
									    <%= f.label :price %><br />
									    <%= f.text_field :price %>
									  </div>

									  <div class="form-group">
									    <%= f.label :part_number %><br />
									    <%= f.text_field :part_number %>
									  </div>

									  <div class="form-group" id='categories'>
                      <%= f.label 'Select category name' %><br />
                      <%= f.collection_select :category_id, Category.get_all_parent, :id, :name,  {:include_blank => 'Select category'}%>
                    </div>

                    <div class="form-group" id='sub_category'>
                      <%= render 'select_category', sub_categories: Category.get_all_sub_categories, selected_value: f.object.sub_category_id %>
                    </div>

                   <div class="form-group" id='sub_category_first'>
                      <%= render 'select_category_first', sub_categories: Category.get_all_sub_categories_level_1, selected_value: f.object.sub_category_first_id %>
                    </div>

                    <div class="form-group" id='sub_category_second'>
                      <%= render 'select_category_second', sub_categories: Category.get_all_sub_categories_level_2, selected_value: f.object.sub_category_second_id %>
                    </div>

									  <%= label_tag 'Product Attributes'%>

                    <%= link_to_add_association 'add more +', f, :products_product_items,
													    'data-association-insertion-node' => "#product_items ol",
													    'data-association-insertion-method' => "append",
													    :wrap_object => Proc.new {|ppi| ppi.build_product_item; ppi } %>
									  <div id='product_items'>
                      <ol>
											  <%= f.fields_for :products_product_items do |pp| %>
												  <%= render 'products_product_item_fields', f: pp %>

												<% end %>

											</ol>
										</div>

									<% end %>

									<ul id="pictures" data-update-url="<%= sort_webmaster_images_url %>" class="pictures_list">
											<%= render @images,:image => @image  %>
									</ul>
                  <%= label_tag 'Upload product images'%>
                  <%= render "upload_image" %>

                  <div class="clear"></div>

									<div class="row">
										<div class="col-lg-8 col-md-8">
											<br />
											<button id='product_submit' class="btn btn-primary btn-save">Save Project</button>
											<%= link_to 'Back', webmaster_products_path, class: 'btn btn-primary' %>
										</div>
									</div>


								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>



<script>

	  $('#new_image').fileupload();
	 //  $('#pictures').sortable({
		//   axis: 'y',
		//   update: function() {
		//     return $.post($(this).data('update-url'), $(this).sortable('serialize'));
		//   }
		// });

		$('#product_submit').on('click',function(){

	  	$('.edit_product').submit();
	  });

	  $('#product_category_id').change(function(){

      var val_id =  $('#product_category_id :selected').val();

      $.ajax({
          type: 'GET',
          url: "<%= search_categories_webmaster_products_path %>",
          data: {"sub_cat_id": val_id, "type": "category" }
      });

    });


</script>

app/views/webmaster/products/new.html.erb
<div id="page-wrapper" >
  <div id="page-inner">
    <div class="row">
      <div class="row">
        <div class="col-lg-12">
          <div class="panel panel-default">
            <div class="panel-heading">
                New Product
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-lg-6">
                  <%= form_for [:webmaster, @product] do |f| %>
                    <% if @product.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

                        <ul>
                        <%  @product.errors.full_messages.each do |msg| %>
                          <li><%= msg %></li>
                        <% end %>
                        </ul>
                      </div>
                    <% end %>

                    <div class="form-group">
                      <%= f.label 'Select brand name' %><br />
                      <%= f.collection_select :brand_id, Brand.all, :id, :name %>

                      <%= link_to 'Add New Brand', add_new_brand_webmaster_brands_path, :remote => true %>
                      <br/>
                      <div id='add_new_brand'>

                      </div>
                      <br/>
                    </div>

                    <div class="form-group">
                      <%= f.label :title %><br />
                      <%= f.text_field :title %>
                    </div>
                    <div class="form-group">
                      <%= f.label :description %><br />
                      <%= f.text_area :description, :cols => "50", :rows => "8" %>
                    </div>

                    <div class="form-group" id='categories'>
                      <%= f.label 'Store' %><br />
                      <%= f.select(:store, options_for_select(Product::STORE))%>
                    </div>

                    <div class="form-group">
                      <%= f.label :product_image %><br />
                      <%= f.file_field :product_image %>
                    </div>

                    <div class="form-group">
                      <%= f.label :price %><br />
                      <%= f.text_field :price %>
                    </div>

                    <div class="form-group">
                      <%= f.label :part_number %><br />
                      <%= f.text_field :part_number %>
                    </div>

                    <div class="form-group" id='categories'>
                      <%= f.label 'Select category name' %><br />
                      <%= f.collection_select :category_id, Category.get_all_parent, :id, :name,  {:include_blank => 'Select category'}%>
                    </div>

                    <div class="form-group" id='sub_category'>
                      <%= render 'select_category', sub_categories: Category.get_all_sub_categories, selected_value: f.object.sub_category_id %>
                    </div>

                   <div class="form-group" id='sub_category_first'>
                      <%= render 'select_category_first', sub_categories: Category.get_all_sub_categories_level_1, selected_value: f.object.sub_category_first_id %>
                    </div>

                    <div class="form-group" id='sub_category_second'>
                      <%= render 'select_category_second', sub_categories: Category.get_all_sub_categories_level_2, selected_value: f.object.sub_category_second_id %>
                    </div>

                    <%= f.hidden_field :token, :value=>@product.token %>

                    <%= f.hidden_field :user_id, :value=>current_user.id %>
                    <%= label_tag 'Product Attributes'%>
                    <br/>
                    <%= link_to_add_association 'Add Attribute', f, :products_product_items,
                              'data-association-insertion-node' => "#product_items ol",
                              'data-association-insertion-method' => "append",
                              :wrap_object => Proc.new {|ppi| ppi.build_product_item; ppi } %>
                    <div id='product_items'>
                      <ol>
                        <%= f.fields_for @product.products_product_items.build do |pp| %>
                          <%#= render 'products_product_item_fields', f: pp %>

                        <% end %>
                      </ol>
                    </div>




                  <% end %>
                  <ul id="pictures" data-update-url="<%= sort_webmaster_images_url %>" class="pictures_list">
                      <%= render @images,:image => @image  %>
                    </ul>
                  <%= label_tag 'Upload product images'%>
                  <%= render "upload_image" %>

                  <div class="clear"></div>

                  <div class="row">
                    <div class="col-lg-8 col-md-8">
                      <br />
                      <button id='product_submit' class="btn btn-primary btn-save">Save Project</button>
                      <%= link_to 'Back', webmaster_products_path, class: "btn btn-primary " %>
                    </div>
                  </div>


                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>




<%= render "attribute_suggestion" %>

<script>

    $('#new_image').fileupload();
   //  $('#pictures').sortable({
    //   update: function() {
    //     return $.post($(this).data('update-url'), $(this).sortable('serialize'));
    //   }
    // });

    $('#product_submit').on('click',function(){
      $('#new_product').submit();
    });

    $('#product_category_id').change(function(){

      var val_id =  $('#product_category_id :selected').val();

      $.ajax({
          type: 'GET',
          url: "<%= search_categories_webmaster_products_path %>",
          data: {"sub_cat_id": val_id, "type": "category" }
      });

     });

</script>

app/views/webmaster/products/search_categories.js.erb
<% if params[:type] == 'category' %>
  $('#sub_category').html('<%= j(render(partial: 'select_category', locals: { sub_categories: @categories, selected_value: "" })) %>');
<% elsif params[:type] == 'sub_category' %>
  $('#sub_category_first').html('<%= j(render(partial: 'select_category_first', locals: { sub_categories: @categories, selected_value: "" })) %>');
<% elsif params[:type] == 'sub_category_first' %>
  $('#sub_category_second').html('<%= j(render(partial: 'select_category_second', locals: { sub_categories: @categories, selected_value: "" })) %>');
<% end %>

app/views/webmaster/products/show.html.erb
<div id="page-wrapper">
  <div id="page-inner">
    <div class="row">
      <div class="col-md-8 col-sm-12 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <span> <%= @product.title %> </span>

            <% if current_user.role == 'super_admin' %>
							<%= link_to 'Edit', edit_webmaster_product_path(@product), class: 'pull-right' %>
						<% end %>
						<span class='pull-right' > | </span>
            <%= link_to 'New', new_webmaster_product_path, class: 'pull-right' %>


          </div>
          <div class="panel-body">
						<p>
						  <b>Title:</b>
						  <%= @product.title %>
						</p>

						<p>
						  <b>Description:</b>
						  <%= @product.description%>
						</p>

						<p>
						  <b>Product main image:</b>
						  <%= image_tag @product.product_image.thumb.url%>
						</p>



						<p>
						  <b>Price:</b>
						  <%= @product.price%>
						</p>

						<p>
						  <b>Brand name:</b>
						  <%= @product.brand_id%>
						</p>

						<p>
						  <b>Part number:</b>
						  <%= @product.part_number %>
						</p>

						<p>
						  <b>Uniq code:</b>
						  <%= @product.uniq_code %>
						</p>

						<p>
						  <b>Image:</b>
						  <% if @product.images.present? %>
						    <% @product.images.each do |img|%>
						      <%= image_tag img.image.thumb.url%>
						    <% end %>
						  <% end %>
						</p>
						<%= link_to 'Back', webmaster_products_path %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>