config/routes.rb
Nmi::Application.routes.draw do

  root :to => 'home#index'

  devise_for :users
  devise_for :users, :path => "webmaster"

  namespace :webmaster do
    resources :categories do
       collection do
        get :category_childrens
      end
    end
    resources :users
    resources :brands do
      collection do
        get :add_new_brand
        post :create_new_brand
      end
    end
    resources :products do
      collection do
        get :search_attribute_name
        get :search_categories
      end
    end
    resources :images do
      collection do
        get :sort
        post :upload_image
        get :delete_image
      end
    end
    get "home/index"
  end

end

app/models/brand.rb
class Brand < ActiveRecord::Base
   attr_accessible :name
   has_one :product
   validates :name, presence: true

end

app/models/webmaster.rb
module Webmaster
  def self.table_name_prefix
    'webmaster_'
  end
end

app/controllers/webmaster/brands_controller.rb
class Webmaster::BrandsController < ApplicationController

  before_filter :authenticate_user!
  load_and_authorize_resource

  layout 'webmaster'
  def index
    @brands = Brand.all
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(params[:brand])
    respond_to do |format|
      if @brand.save
        if params[:commit] == "Add Brand"
          format.html { redirect_to new_webmaster_product_path }
        else
           format.html { redirect_to webmaster_brand_path(@brand), notice: 'Brand was successfully created.' }
        end
        #format.json { render json: @webmaster_category, status: :created, location: @webmaster_category }
      else
        format.html { render action: "new" }
      end
    end
  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def show
     @brand = Brand.find(params[:id])
  end

  def update
    @brand = Brand.find(params[:id])

    respond_to do |format|
      if @brand.update_attributes(params[:brand])
        format.html { redirect_to webmaster_brand_path(@brand), notice: 'Brand was successfully updated.' }
        #format.json { head :no_content }
      else
        format.html { render action: "edit" }
        #format.json { render json: @webmaster_category.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_new_brand
    @brand = Brand.new
    respond_to do |format|
      format.js
    end
  end



  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to webmaster_brands_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/webmaster/categories_controller.rb
class Webmaster::CategoriesController < ApplicationController
 before_filter :authenticate_user!
 #before_filter :authorize_admin
 load_and_authorize_resource

 layout 'webmaster'

  # GET /webmaster/categories
  # GET /webmaster/categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
     # format.json { render json: @webmaster_categories }
    end
  end

  def category_childrens
    @parent_category = Category.get_all_parent
  end

  # GET /webmaster/categories/1
  # GET /webmaster/categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      #format.json { render json: @webmaster_category }
    end
  end

  # GET /webmaster/categories/new
  # GET /webmaster/categories/new.json
  def new
    @category =  Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /webmaster/categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /webmaster/categories
  # POST /webmaster/categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to webmaster_category_path(@category), notice: 'Category was successfully created.' }
        #format.json { render json: @webmaster_category, status: :created, location: @webmaster_category }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /webmaster/categories/1
  # PUT /webmaster/categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to webmaster_category_path(@category), notice: 'Category was successfully updated.' }
        #format.json { head :no_content }
      else
        format.html { render action: "edit" }
        #format.json { render json: @webmaster_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webmaster/categories/1
  # DELETE /webmaster/categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to webmaster_categories_url }
      format.json { head :no_content }
    end
  end

  protected

  def authorize_admin
    authorize! :manage, :all
  end
end

app/controllers/webmaster/home_controller.rb
class Webmaster::HomeController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  layout 'webmaster'
  def index
  end
end

app/controllers/webmaster/images_controller.rb
class Webmaster::ImagesController < ApplicationController

	def delete_image
    @image = Image.find(params[:id])
    @images = Image.where(:product_token => @image.product_token).order("position")
    @image.destroy
    respond_to do |format|
      format.js 
    end
  end

  def upload_image
    @image = Image.create(params[:image])
    @images = Image.where(:product_token => @image.product_token).order("position")
  end 

  def sort
    params[:image].each_with_index do |id, index|
      Image.update_all({position: index+1}, {id: id})
    end
    render nothing: true
  end

end

app/controllers/webmaster/products_controller.rb
class Webmaster::ProductsController < ApplicationController
 before_filter :authenticate_user!
 load_and_authorize_resource
 layout 'webmaster'


  # GET /webmaster/categories
  # GET /webmaster/categories.json
  def index
    if current_user.role == 'super_admin'
      @products = Product.all
    else
      @products = current_user.products
    end

    respond_to do |format|
      format.html # index.html.erb
     # format.json { render json: @webmaster_categories }
    end
  end

  # GET /webmaster/categories/1
  # GET /webmaster/categories/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      #format.json { render json: @webmaster_category }
    end
  end

  # GET /webmaster/categories/new
  # GET /webmaster/categories/new.json
  def new
    @product =  Product.new
    if @product.token.nil?
      @product.token = @product.generate_token
    end
    @images = Image.where(:product_token => @product.token).order("position")
    respond_to do |format|
      format.html # new.html.erb
      #format.json { render json: @product }
    end
  end

  # GET /webmaster/categories/1/edit
  def edit
    @product = Product.find(params[:id])
    @images = @product.images.order('position')
  end

  # POST /webmaster/categories
  # POST /webmaster/categories.json
  def create
    @product = Product.new(params[:product])
    @images = Image.where(:product_token => params[:product][:token])
    respond_to do |format|
      if @product.save
        @images.each do |image|
          image.update_attributes(imageable_id: @product.id, imageable_type: @product.class.name)
        end
        format.html { redirect_to webmaster_product_path(@product), notice: 'Product was successfully created.' }
        #format.json { render json: @webmaster_category, status: :created, location: @webmaster_category }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /webmaster/categories/1
  # PUT /webmaster/categories/1.json
  def update
    @product = Product.find(params[:id])
    @images = Image.where(:product_token => params[:product][:token])
    respond_to do |format|
      if @product.update_attributes(params[:product])
        @images.each do |image|
          image.update_attributes(imageable_id: @product.id, imageable_type: @product.class.name)
        end
        format.html { redirect_to webmaster_product_path(@product), notice: 'Product was successfully updated.' }
        #format.json { head :no_content }
      else
        format.html { render action: "edit" }
        #format.json { render json: @webmaster_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /webmaster/categories/1
  # DELETE /webmaster/categories/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to webmaster_products_url }
      format.json { head :no_content }
    end
  end

  def search_attribute_name
    @results =  ProductItem.where("name LIKE ?", "%#{params[:q]}%")
    respond_to do |format|
      format.json
    end
  end

  def search_categories
    @categories = Category.where(:id=> params[:sub_cat_id]).first.children
  end
end

app/controllers/webmaster/users_controller.rb
class Webmaster::UsersController < ApplicationController
  before_filter :authenticate_user!
  #before_filter :authorize_admin
  load_and_authorize_resource
  layout 'webmaster'
  #before_filter :authenticate_user!
  def index
  	@users = User.all
  end

  def edit
  	@user = User.find(params[:id])
  end

  def show
  	 @user = User.find(params[:id])
  end

  def update
	  @user = User.find(params[:id])

	  if @user.update_attributes(params[:user])
	    redirect_to webmaster_user_url(@user)
	  else
	    render 'edit'
	  end
  end
  def destroy
  	@user = User.find(params[:id])
  	@user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
    end
  end

  protected
  # def authorize_admin
  #   authorize! :manage, :all
  # end

end

app/helpers/webmaster/brands_helper.rb
module Webmaster::BrandsHelper
end

app/helpers/webmaster/categories_helper.rb
module Webmaster::CategoriesHelper
end

app/helpers/webmaster/home_helper.rb
module Webmaster::HomeHelper
end

app/helpers/webmaster/image_helper.rb
module Webmaster::ImageHelper
end

app/helpers/webmaster/users_helper.rb
module Webmaster::UsersHelper
end

app/views/webmaster/brands/_add_new_brand.html.erb
<div>
  <%= form_for([:webmaster, brand], remote: true) do |f| %>
    <div class="form-group">
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.submit "Add Brand" %>
    </div>
  <% end %>
</div>
<br/>

<script>
  var f1 = new LiveValidation('brand_name');
  f1.add( Validate.Presence );

</script>

app/views/webmaster/brands/add_new_brand.js.erb
$('#add_new_brand').append('<%= j(render(partial: 'add_new_brand', locals: { brand: @brand })) %>');

app/views/webmaster/brands/create_new_brand.js.erb
alert(1);

app/views/webmaster/brands/edit.html.erb
<div id="page-wrapper" >
  <div id="page-inner">
    <div class="row">
      <div class="row">
        <div class="col-lg-12">
          <div class="panel panel-default">
            <div class="panel-heading">
                Edit Brand
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-lg-6">
                  <%= form_for [:webmaster, @brand] do |f| %>
                    <% if @brand.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

                        <ul>
                        <%  @brand.errors.full_messages.each do |msg| %>
                          <li><%= msg %></li>
                        <% end %>
                        </ul>
                      </div>
                    <% end %>

                    <div class="form-group">
                      <%= f.label :name %><br />
                      <%= f.text_field :name %>
                    </div>


                    <div class="form-group">
                      <%= f.submit %>
                    </div>
                  <% end %>



                  <%= link_to 'Back', webmaster_brands_path %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/webmaster/brands/index.html.erb
<div id="page-wrapper">
  <div id="page-inner">
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading">
             <span> Brand Lists </span>
             <%= link_to 'New', new_webmaster_brand_path, class: 'pull-right' %>
          </div>
          <div class="panel-body">
            <div class="table-responsive">

              <table class="table table-striped table-bordered table-hover">
                <tr>
                  <th>Name</th>
                  <th></th>
                  <th></th>
                  <th></th>
                </tr>

              <% @brands.each do |b| %>
                <tr>
                  <td><%= b.name %></td>
                  <td><%= link_to 'Show', webmaster_brand_path(b) %></td>
                  <td><%= link_to 'Edit', edit_webmaster_brand_path(b) %></td>
                  <td><%= link_to 'Destroy', webmaster_brand_path(b), confirm: 'Are you sure?', method: :delete %></td>
                </tr>
              <% end %>
              </table>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/webmaster/brands/new.html.erb
<div id="page-wrapper" >
  <div id="page-inner">
    <div class="row">
      <div class="row">
        <div class="col-lg-12">
          <div class="panel panel-default">
            <div class="panel-heading">
                New Brand
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-lg-6">
                  <%= form_for [:webmaster, @brand] do |f| %>
                    <% if @brand.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

                        <ul>
                        <%  @brand.errors.full_messages.each do |msg| %>
                          <li><%= msg %></li>
                        <% end %>
                        </ul>
                      </div>
                    <% end %>

                    <div class="form-group">
                      <%= f.label :name %><br />
                      <%= f.text_field :name %>
                    </div>


                    <div class="form-group">
                      <%= f.submit %>
                    </div>
                  <% end %>



                  <%= link_to 'Back', webmaster_brands_path %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/webmaster/brands/show.html.erb
<div id="page-wrapper">
  <div id="page-inner">
    <div class="row">
      <div class="col-md-8 col-sm-12 col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= @brand.name %>
          </div>
          <div class="panel-body">
            <p>
              <b>Name:</b>
              <%= @brand.name %>
            </p>

            <%= link_to 'Edit', edit_webmaster_brand_path(@brand) %> |
            <%= link_to 'Back', webmaster_brands_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>