config/routes.rb
Nmi::Application.routes.draw do

  root :to => 'home#index'

  devise_for :users
  devise_for :users, :path => "webmaster"

  namespace :webmaster do
    resources :categories do
       collection do
        get :category_childrens
      end
    end
    resources :users
    resources :brands do
      collection do
        get :add_new_brand
        post :create_new_brand
      end
    end
    resources :products do
      collection do
        get :search_attribute_name
        get :search_categories
      end
    end
    resources :images do
      collection do
        get :sort
        post :upload_image
        get :delete_image
      end
    end
    get "home/index"
  end

end

app/views/layouts/_backend_header.html.erb
<div id="wrapper">
  <nav class="navbar navbar-default top-navbar" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= webmaster_users_path %>"><%= image_tag "logo.png" %></a>
    </div>

    <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
          <% if current_user.role == 'super_admin' %>
            <a href="<%= webmaster_users_path %>">User Lists
            </a>
          <% end %>
            <!-- /.dropdown-messages -->
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
          <a href="<%= webmaster_products_path %>">Product
            </a>
        </li>
        <li class="dropdown">
          <% if current_user.role == 'super_admin' %>
            <a href="<%= webmaster_categories_path %>">Category
            </a>
          <% end %>
        </li>

        <li class="dropdown">
          <% if current_user.role == 'super_admin' %>
            <a href="<%= webmaster_brands_path %>">Brand
            </a>
          <% end %>
        </li>

        <li class="dropdown">
          <% if current_user.role == 'super_admin' %>
            <a href="<%= category_childrens_webmaster_categories_path %>">Category Childrens
            </a>
          <% end %>
        </li>
        <!-- /.dropdown -->

        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">
                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="<%=webmaster_user_path(current_user)%>"><i class="fa fa-user fa-fw"></i> User Profile</a>
                </li>
                <li><a href="<%=webmaster_users_path%>"><i class="fa fa-gear fa-fw"></i> Settings</a>
                </li>
                <li class="divider"></li>
                <li><a  href="<%= destroy_user_session_path %>", data-method= 'get'><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
  </nav>
  <!--/. NAV TOP  -->
  <nav class="navbar-default navbar-side" role="navigation">
      <div class="sidebar-collapse">
          <ul class="nav" id="main-menu">
              <% if current_user.role == 'super_admin' %>
                <li>
                  <a class="active-menu" href="<%= webmaster_users_path %>"><i class="fa fa-dashboard"></i> Users</a>
                </li>
                <li>
                  <a href="<%= webmaster_categories_path %>"><i class="fa fa-desktop"></i> Categories</a>
                </li>
                 <li>
                   <a href="<%= webmaster_brands_path %>"><i class="fa fa-bar-chart-o"></i> Brands</a>
                 </li>
              <% end %>
		          <li>
                  <a href="<%= webmaster_products_path %>"><i class="fa fa-bar-chart-o"></i> Products</a>
              </li>


          </ul>

      </div>

  </nav>

</div>

app/views/layouts/_frontend_footer.html.erb
<footer>
	<div class="container-fluid footer-link">
  	<div class="row-fluid">
    	<div class="span6">
      	<div class="row-fluid">
        	<div class="span4">
            <%= image_tag "footer-logo.png", {title: "Non Moving Items"} %>
          </div>
        	<div class="span4">
            <ul>
              <li><a href="#">About Us</a></li>
              <li><a href="#">Contact Us</a></li>
              <li><a href="#">Customer Service</a></li>
              <li><a href="#">Advertise With Us</a></li>
              <li><a href="#">Buyers Toolkit</a></li>
              <li><a href="#">Seller Toolkit</a></li>
            </ul>
          </div>
          <div class="span4">
            <ul>
              <li><a href="#">Technical Help</a></li>
              <li><a href="#">Privacy policy</a></li>
              <li><a href="#">Terms of use</a></li>
              <li><a href="#">Disclaimer policy</a></li>
              <li><a href="#">Site Map</a></li>
            </ul>
          </div>
        </div>
      </div>            	
    	<div class="span3">
        <h2 class="footer-heading">NewsLetter!</h2>
        <p>sign up for emails to receive email only promotions</p>
        <div class="footer-search">
        	<input type="text" placeholder="Enter Email" class="pull-left">
          <input type="button" value="Subscribe" title="Subscribe" class="pull-left">
          <span class="clr"></span>
        </div>
      </div>
      <div class="span3">
      	<h2 class="footer-heading">Connect With Us</h2>
        <a href="#" class="footer-icon footer-tw" title="Twitter">&nbsp;</a>
        <a href="#" class="footer-icon footer-fb" title="Facebook">&nbsp;</a>
        <a href="#" class="footer-icon footer-in" title="Linkedin">&nbsp;</a>
        <a href="#" class="footer-icon footer-yo" title="you Tube">&nbsp;</a>
        <a href="#" class="footer-icon footer-pi" title="Pinterest">&nbsp;</a>
        <span class="clr"></span>
      </div>                
    </div>
  </div>
  <div class="copy-right">&copy; Copyright 2015 Non Moving Items. All rights reserved.</div>
</footer>

app/views/layouts/_frontend_header.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container-fluid">
      <ul class="nav nav-tabs minor-menu">
        <li class="dropdown">
          <% if !user_signed_in?%>
          	<a href="<%= new_user_session_path %>", title="Login">Login</a>
            <ul id="login-dropdown" class="dropdown-menu">
              <form id="login-form" action="">
                <h2 class="form-heading login-form-heading">Login here</h2>
                <div class="form-group">
                  <input type="text" placeholder="Courriel" name="" class="form-control required" id="login" value="">
                </div>
                <div class="form-group">
                  <input type="password" placeholder="" name="" class="form-control required" id="password">
                </div>
                <div class="checkbox pull-left">
                  <label for="remember-me">
                    <input type="checkbox" name="" id="remember-me" class="optional">Remember me
                  </label>
                </div>
                <p class="forgot-password pull-right">
                	<a href="#">Forgot Password?</a>
                </p>
                <span class="clearfix"></span>
                <div class="button-section">
                	<input type="button" id="button_login" value="Login" class="buttons red-btn " title="Login">
                	<input type="button" id="button_login" value="Register" class="buttons grey-btn " title="Register">
                </div>
              </form>
            </ul>
          <% else %>
            <a href="<%= destroy_user_session_path %>", data-method= 'delete', title="Logout">Logout</a>
          <% end %>
        </li>
      </ul>
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="nav-collapse collapse">
        <ul class="nav pull-right">
          <li class="active"><%= link_to "Home", root_path %></li>
          <li><%= link_to "About Us", root_path %></li>
          <li><%= link_to "My Account",  edit_user_registration_path %></li>
          <li><%= link_to "Faq", root_path %></li>
          <li><%= link_to "Advance Search", root_path %></li>
          <li><%= link_to "Vastu Consultancy", root_path %></li>
          <li><%= link_to "Contact Us", root_path, class: "last-child" %></li>
        </ul>
      </div><!--/.nav-collapse -->

    </div>
  </div>
</div>
<%= render partial: "shared/flash_messages", flash: flash %>
<div class="header container-fluid">
  <div class="row-fluid">
  	<div class="span3">
  		<a class="brand logo" href="<%= root_path %>">
        <%= image_tag "logo.jpg", {title: "Non Moving Items"} %>
      </a>
  	</div>
    <div class="span9">
      <div class="top-search-section pull-right span6">
      	<div class="row-fluid">
      		<div class="span6">
            <span class="phone-number">LIVE HELP - <i>9827011111</i></span>
          </div>
          <div class="span6">
              <div class="search-box">
                  <input type="text" name="" placeholder="Search" id="">
                  <input type="button" value="" class="icon-search search-button">
              </div>
          </div>
        </div>
      </div>
      <span class="clr"></span>
      <button type="button" class="btn btn-navbar pull-right" data-toggle="collapse" data-target=".nav-collapse-two"> Menu </button>
  		<div class="nav-collapse-two collapse">
        <ul class="header-menu pull-right">
            <li class="active"><a href="#">New Item Store</a></li>
            <li><a href="#">USED Item Store</a></li>
            <li><a href="#">New Arrivals</a></li>
            <li><a href="#">Technical Info</a></li>
            <li><a href="#">Post Inventory</a></li>
            <li><a href="#">Inventory Calculator</a></li>
        </ul>
      </div>

    </div>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	  <meta charset="utf-8">
	  <title>Non Moving Items</title>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <meta name="description" content="">
	  <meta name="author" content="">
	  <!-- Le styles -->
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
	  <%= render "layouts/frontend_header" %>
		<%= yield %>
		<%= render "layouts/frontend_footer" %>
	</body>
</html>

app/views/layouts/webmaster.html.erb
<!DOCTYPE html>
<html>
  <head>
	  <meta charset="utf-8">
	  <title>Non Moving Iteams</title>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <meta name="description" content="">
	  <meta name="author" content="">
	  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
	  <!-- Le styles -->
	  <%= stylesheet_link_tag    "webmaster", :media => "all" %>
	  <%= javascript_include_tag "webmaster" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
	  <%= render "layouts/backend_header" %>
    <%= render partial: "shared/flash_messages", flash: flash %>
	  <%= yield %>
	</body>
</html>